name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt -y update&&sudo apt -y install netcat php*-imap php*-mbstring php*-mcrypt php*-sockets
        sudo nc -l localhost 3143 & sudo nc localhost 3143
        composer install
    - name: Run phpunit tests
      run: phpunit
