name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install dependencies
      run: |
        sudo apt install php*-imap php*-mbstring php*-mcrypt
        composer install
    - name: Run phpunit tests
      run: phpunit
